### ISSUE TITLE
Add any Sorting Algorithm of your choice.

### ISSUE THREAD

**Issue by tulika-99** [tulika-99/sorting-algorithms#1]
# You can add any sorting algorithm of your choice in any language.

1. Choose an algorithm that isn't present in the repo.
**(Note: you can implement the same algorithm in a different language)**
2. Check the comments to make sure no one is already working on it.
3. Comment the algorithm and language that you chose.
4. Check the repo guidelines for steps and format and start working.

Note : you don't necessarily need to know how to code , you can even write algorithms and its explanations in a text file for those algos who are missing it and help us in documentation.

Please refrain from adding spam PR's . I will mark them as invalid !!

**Comment by cjdunteman** [comment]
Will do an example of Breadth First Search in Java

**Comment by mugnimaestra** [comment]
I did Bubble sort for Javascript here https://github.com/tulika-99/sorting-algorithms/pull/8

**Comment by smumen3** [comment]
Bubble Sort Java

**Comment by smumen3** [comment]
Insertion Sort Java

**Comment by myselfronin** [comment]
Heap Sort Java

**Comment by johnli01** [comment]
Bogo Sort

**Comment by androidmason** [comment]
Bubble Sort Scala

**Comment by sahiljamwal** [comment]
Merge Sort in Java

**Comment by sksuryan** [comment]
Insertion Sort in C++

**Comment by pBouillon** [comment]
Bogosort done here ! #25

**Comment by hientranea** [comment]
I added InsertionSort in Dart here https://github.com/tulika-99/sorting-algorithms/pull/28

**Comment by pavitrawalia** [comment]
I have done insertion sort in Python3

**Comment by Shyndard** [comment]
Heap sort in typescript (JS)

**Comment by Shyndard** [comment]
Counting sort in TypeScript

**Comment by Shyndard** [comment]
Counting sort in Java

**Comment by Ritesh-Ag** [comment]
Bubble sort in C++

**Comment by Ritesh-Ag** [comment]
Selection Sort in C++

**Comment by Akshayy99** [comment]
I added mergeSort written in C++.

**Comment by mvp223** [comment]
Selection Sort in Java

**Comment by johnli01** [comment]
BogoSort C++

**Comment by jsedano** [comment]
Selection Sort in Java

**Comment by divyamagwl** [comment]
I added Merge Sort in C

**Comment by entowan** [comment]
Added Gnome sort in Python

**Comment by ayz975** [comment]
added radix sort in java

**Comment by robertatiriticco** [comment]
Bubble sort C

**Comment by liminm** [comment]
I will do Cocktail Sort in Python

**Comment by RohanMenon** [comment]
Added Pancake Sort here, #57 😄

**Comment by SilviuCAnton** [comment]
I will add insertion sort - javascript

**Comment by codebreaker-00** [comment]
I will add bubble sort in C

**Comment by ambika1101** [comment]
merge sort in python

**Comment by ambika1101** [comment]
heap sort in python

**Comment by codebreaker-00** [comment]
I'm a beginner programmer I know only C(basic-moderate). I don't know
Python.

**Comment by jsedano** [comment]
Will add pancake sort in Java

**Comment by nandarustam** [comment]
BubbleSort in Kotlin added in #74

**Comment by nandarustam** [comment]
Hi @tulika-99, ping kindly on the PR for Sort algorithms in Kotlin, #74 #77 #78 #79 #80

**Comment by subramanian-m** [comment]
@tulika-99 I have added CocktailSort in Java and raised a pull request. #91

**Comment by SimonHuet** [comment]
Hey, I've added shellShort function in JS :)

**Comment by sarahshrivastava** [comment]
Bubble sort in python

**Comment by bharati-21** [comment]
I'd like to work on cocktail Sort using C

**Comment by gateway2rohan** [comment]
I added Insertion Sort in C#.

**Comment by ayz975** [comment]
Radix Sort C# #100

**Comment by tulika-99** [comment]
@codebreaker-00  no problem u can add a text file containing explanation of some algorithms which are missing it or for some entirely new type of sorting algorithm that h might have read about somewhere!

**Comment by ayz975** [comment]
Radix Sort Python #101

**Comment by shiprakesarwani** [comment]
Merge Sort C# https://github.com/tulika-99/sorting-algorithms/pull/111

**Comment by gateway2rohan** [comment]
Quick Sort C# #112

**Comment by kanika359** [comment]
I will implement Cocktail Sort in cpp and raise a PR!

**Comment by micaelalex** [comment]
Added Bitonic Sort in Java #124

**Comment by micaelalex** [comment]
Added Bitonic Sort explanation file in txt, as requested. #125

**Comment by ipefaur** [comment]
I'll try bucket sort in Java.

**Comment by kpencak** [comment]
Added Selection sort in Matlab :) #130

**Comment by kpencak** [comment]
I will add Pigeonhole Sort in Java

**Comment by werewolf-spirit** [comment]
I will add Bubble Sort in C

**Comment by werewolf-spirit** [comment]
I'll also add bubble sort in Java

**Comment by werewolf-spirit** [comment]
I will also add selection sort in java

**Comment by murilopereirame** [comment]
Bubble sort C#

**Comment by pedroandrades** [comment]
Added Sleep Sort implementation in Java

**Comment by shrinathjoshi** [comment]
Added Bucket Sort implementation in Java

**Comment by Mohitkumar6122** [comment]
Tim Sort Algorithim implemented in Python

**Comment by sonukushwaha403** [comment]
is this issue open can i work on it with java "QUICK SORT"

**Comment by tulika-99** [comment]
@sonukushwaha403 Sorry It has already been implemented .

**Comment by sonukushwaha403** [comment]
then can i do quick sort in python???

**Comment by sonukushwaha403** [comment]
then can i do quick sort in python???

**Comment by tulika-99** [comment]
@sonukushwaha403 pls check the repo and then choose. Most of the stuff are already implemented by now

**Comment by tulika-99** [comment]
Thank you all for your contributions !! Hope it was a learning experience for you all. 
See you guys next month for Hacktoberfest 2020 ✌🏻
