### ISSUE TITLE
Language specific packages

### ISSUE THREAD

**Issue by androidmason** [tulika-99/sorting-algorithms#16]
Is it possible to create packages for each language and have all language specific algorithms within the package ?
It might also be helpful to group it based on algorithms. 
 
With increasing implementation it might get difficult to search

**Comment by tulika-99** [comment]
That is a great suggestion .
cool I'll do that!!

**Comment by tulika-99** [comment]
Done pls check it out and thnx again although I did it according to the algos.

**Comment by androidmason** [comment]
Great..!! Looks perfect 👍
