### ISSUE TITLE
Add any remaining Sorting Algorithms of your choice.

### ISSUE THREAD

**Issue by tulika-99** [tulika-99/sorting-algorithms#160]
## You can add any Sorting Algorithm of your choice in any language.

- Choose an algorithm that isn't already present in the repo.
- or implement the same algorithm in a different language.( Pls do check if its already present or not)
- or write a MD file with the explanation, theory, time and space complexities with examples.

## What all to keep in mind
- Check the comments to make sure no one is already working on it.
- Comment the algorithm and language that you chose.
- Check the repo guidelines for steps and format and start working.
- you don't necessarily need to know how to code , you can even write algorithms and its explanations in a text file for those algos who are missing it and help us in documentation.
- Please refrain from adding spam PR's . They will be marked as invalid !!

## Note 

Since this repo is a year old, most of the algos are already present. But some not so common algos are still left to be implemented in various different languages. This might serve as a research assignment for some.

**Comment by kchatr** [comment]
Hey, could I implement selection sort in Dart? It's not already present, and Dart is the fastest growing language, so I think it would be appropriate :)

**Comment by Rj-coder-iitian** [comment]
@tulika-99 I would like to implement algorithms in bubble, selection, insertion, merge sort. please assign this to me.
I will be using C language.

**Comment by tulika-99** [comment]
@Rj-coder-iitian I think almost all of them are already present. plz check the repo first and then select. If you would like somthing in C you can try tim Sort, tree sort, cycle sort, bucket sort, radix sort etc..

**Comment by Rj-coder-iitian** [comment]
okay.

**Comment by aastha-b** [comment]
Hey can I implement it using java.

**Comment by kchatr** [comment]
@aastha-b Sorry to be the bearer of bad news but it's already been implemented in Java.

**Comment by aastha-b** [comment]
can I implement it using C++ or python?

**Comment by tulika-99** [comment]
@Mohit-Vishwakarma Sure! You can add the analysis as of now and add the implementation later

**Comment by tulika-99** [comment]
@aastha-b Plz check the repo 1st and then decide and comment.

**Comment by Kemalele** [comment]
I would like to implement brick sort on Golang. @tulika-99

**Comment by anirudh2019** [comment]
@tulika-99 Can I implement KWay Merge Sort in Python or java?

**Comment by Vaibhav22-Dev** [comment]
hay, i would like to implement shell sort in java

**Comment by tulika-99** [comment]
@Vaibhav22-Dev Those are already done. Stooge sort, K way merge sort,  cycle sort, are still left for java.

**Comment by cuber485** [comment]
Can I implement heap sort, radix sort and brick sort in C?

**Comment by tulika-99** [comment]
@Kemalele @cuber485 @anirudh2019 yes u guys can work on these.

**Comment by cuber485** [comment]
@tulika-99  Added all three algorithms in C. check the pull request. Thank you.

**Comment by ParanoidWolf** [comment]
Implemented Bubble Sort algorithm using Bash #182 . Kindly merge the pull request. Thanks.

**Comment by Karan-Dhingra** [comment]
I have inserted Linear Sort which was missing. I have done linear sort in C++ Language

**Comment by tulika-99** [comment]
@Karan-Dhingra I have reviewed ur PR. Pls look for something else. There is no such thing as linear sort.

**Comment by Karan-Dhingra** [comment]
Yes today only I will change

**Comment by Karan-Dhingra** [comment]
I have added Linear Search in c++

**Comment by JukMR** [comment]
Hi! Could I implement the HeapSort algorithm in python3? Thanks in advance!

**Comment by JukMR** [comment]
> Hi! Could I implement the HeapSort algorithm in python3? Thanks in advance!

Sorry, I didn't see it was already implemented. Could I implement the TimSort algorithm in Python then? I couldn't find it in the repo. 
Thanks in advance!!
