### ISSUE TITLE
Add any remaining Sorting Algorithm of your choice.

### ISSUE THREAD

**Issue by tulika-99** [tulika-99/sorting-algorithms#197]
## You can add any Sorting Algorithm of your choice in any language.

- Choose an algorithm that isn't already present in the repo.
- or implement the same algorithm in a different language.( Pls do check if its already present or not)
- or write a MD file with the explanation, theory, time and space complexities with examples.

## What all to keep in mind
- Check the comments to make sure no one is already working on it. (Check the **[List Of Whats Done.md](https://github.com/tulika-99/sorting-algorithms/blob/master/List%20Of%20Whats%20done.md)** file)
- Comment the algorithm and language that you chose.
- Check the repo guidelines for steps and format and start working.
- you don't necessarily need to know how to code , you can even write algorithms and its explanations in a text file for those algos who are missing it and help us in documentation.
- Please refrain from adding spam PR's . They will be marked as **invalid** !!

## Note 

Since this repo is old, most of the algos are already present. But some not so common algos are still left to be implemented in various different languages. This might serve as a research assignment for some.

**Comment by mk1107** [comment]
Want to add comb sort algo in cp and python

**Comment by SamikshyaMstar** [comment]
Hey @tulika-99  can I add counting sort in JAVA?

**Comment by SamikshyaMstar** [comment]
Hi, made PR #203 pls merge it @tulika-99.

**Comment by SamikshyaMstar** [comment]
@tulika-99 kindly merge PR #203 made.

**Comment by SemwalShaurya** [comment]
Hi @tulika-99 !
I want to work on TimSort for C++
